local L0, L1, L2, L3
L0 = 180
MAX_MINIONS_EVER = L0
L0 = 100
TEAM_ORDER = L0
L0 = 200
TEAM_CHAOS = L0
L0 = 1
ORDER_HQ = L0
L0 = 2
CHAOS_HQ = L0
L0 = 2
FRONT_TOWER = L0
L0 = 1
BACK_TOWER = L0
L0 = 3
HQ_TOWER2 = L0
L0 = 4
HQ_TOWER1 = L0
L0 = 1
CENTER_LANE = L0
L0 = -90000000
INITIAL_TIME_TO_SPAWN = L0
L0 = 0
MINION_HEALTH_DENIAL_PERCENT = L0
L0 = 64
MELEE_EXP_GIVEN = L0
L0 = 18
MELEE_GOLD_GIVEN = L0
L0 = 32
ARCHER_EXP_GIVEN = L0
L0 = 14
ARCHER_GOLD_GIVEN = L0
L0 = 100
CASTER_EXP_GIVEN = L0
L0 = 25
CASTER_GOLD_GIVEN = L0
L0 = 100
SUPER_EXP_GIVEN = L0
L0 = 25
SUPER_GOLD_GIVEN = L0
L0 = 0
MELEE_HEALTH_UPGRADE = L0
L0 = 0
MELEE_DAMAGE_UPGRADE = L0
L0 = 0
MELEE_GOLD_UPGRADE = L0
L0 = 0
MELEE_EXP_UPGRADE = L0
L0 = 0
ARCHER_HEALTH_UPGRADE = L0
L0 = 0
ARCHER_DAMAGE_UPGRADE = L0
L0 = 0
ARCHER_GOLD_UPGRADE = L0
L0 = 0
ARCHER_EXP_UPGRADE = L0
L0 = 0
CASTER_HEALTH_UPGRADE = L0
L0 = 0
CASTER_DAMAGE_UPGRADE = L0
L0 = 0
CASTER_GOLD_UPGRADE = L0
L0 = 0
CASTER_EXP_UPGRADE = L0
L0 = 0
SUPER_HEALTH_UPGRADE = L0
L0 = 0
SUPER_DAMAGE_UPGRADE = L0
L0 = 0
SUPER_GOLD_UPGRADE = L0
L0 = 0
SUPER_EXP_UPGRADE = L0
L0 = 10
MAXIMUM_MELEE_GOLD_BONUS = L0
L0 = 10
MAXIMUM_ARCHER_GOLD_BONUS = L0
L0 = 20
MAXIMUM_CASTER_GOLD_BONUS = L0
L0 = 20
MAXIMUM_SUPER_GOLD_BONUS = L0
L0 = 180
UPGRADE_MINION_TIMER = L0
L0 = 100
MELEE_HEALTH_INHIBITOR = L0
L0 = 10
MELEE_DAMAGE_INHIBITOR = L0
L0 = 0
MELEE_GOLD_INHIBITOR = L0
L0 = 0
MELEE_EXP_INHIBITOR = L0
L0 = 60
ARCHER_HEALTH_INHIBITOR = L0
L0 = 18
ARCHER_DAMAGE_INHIBITOR = L0
L0 = 0
ARCHER_GOLD_INHIBITOR = L0
L0 = 0
ARCHER_EXP_INHIBITOR = L0
L0 = 200
CASTER_HEALTH_INHIBITOR = L0
L0 = 25
CASTER_DAMAGE_INHIBITOR = L0
L0 = 0
CASTER_GOLD_INHIBITOR = L0
L0 = 0
CASTER_EXP_INHIBITOR = L0
L0 = 0
SUPER_HEALTH_INHIBITOR = L0
L0 = 0
SUPER_DAMAGE_INHIBITOR = L0
L0 = 0
SUPER_GOLD_INHIBITOR = L0
L0 = 0
SUPER_EXP_INHIBITOR = L0
L0 = 1250
EXP_GIVEN_RADIUS = L0
L0 = 360
DISABLE_MINION_SPAWN_BASE_TIME = L0
L0 = 90
DISABLE_MINION_SPAWN_MAG_TIME = L0
L0 = -1
LAST_WAVE = L0
L0 = "none"
SPECIAL_MINION_MODE = L0
L0 = false
HQTurretAttackable = L0
L0 = {}
L0.MeleeMinionName = "Blue_Minion_Basic"
L0.ArcherMinionName = "Blue_Minion_Wizard"
L0.CasterMinionName = "Blue_Minion_MechCannon"
L0.SuperMinionName = "Blue_Minion_MechMelee"
OrderNames = L0
L0 = {}
L0.MeleeMinionName = "Red_Minion_Basic"
L0.ArcherMinionName = "Red_Minion_Wizard"
L0.CasterMinionName = "Red_Minion_MechCannon"
L0.SuperMinionName = "Red_Minion_MechMelee"
ChaosNames = L0
L0 = {}
L0.WaveSpawnRate = 0
L0.NumOfMeleeMinionsPerWave = 0
L0.NumOfArcherMinionsPerWave = 0
L0.NumOfCasterMinionsPerWave = 0
L0.NumOfSuperMinionsPerWave = 0
L0.SingleMinionSpawnDelay = 0
L0.DidPowerGroup = 0
L0.MeleeMinionName = 0
L0.ArcherMinionName = 0
L0.CasterMinionName = 0
L0.SuperMinionName = 0
SpawnTable = L0
L0 = {}
L0.IsDestroyed = false
L0.MeleeHPBonus = 0
L0.MeleeDamageBonus = 0
L0.MeleeGoldBonus = 0
L0.MeleeExpBonus = 0
L1 = MELEE_EXP_GIVEN
L0.MeleeExpGiven = L1
L1 = MELEE_GOLD_GIVEN
L0.MeleeGoldGiven = L1
L0.ArcherHPBonus = 0
L0.ArcherDamageBonus = 0
L0.ArcherGoldBonus = 0
L0.ArcherExpBonus = 0
L1 = ARCHER_EXP_GIVEN
L0.ArcherExpGiven = L1
L1 = ARCHER_GOLD_GIVEN
L0.ArcherGoldGiven = L1
L0.CasterHPBonus = 0
L0.CasterDamageBonus = 0
L0.CasterGoldBonus = 0
L0.CasterExpBonus = 0
L1 = CASTER_EXP_GIVEN
L0.CasterExpGiven = L1
L0.SuperHPBonus = 0
L0.SuperDamageBonus = 0
L0.SuperGoldBonus = 0
L0.SuperExpBonus = 0
L1 = SUPER_EXP_GIVEN
L0.SuperExpGiven = L1
L0.NumOfSpawnDisables = 0
L0.WillSpawnSuperMinion = 0
L0.MeleeMinionName = 0
L0.RangedMinionName = 0
L0.CasterMinionName = 0
L1 = CASTER_GOLD_GIVEN
L0.CasterGoldGiven = L1
L0.SuperMinionName = 0
L1 = CASTER_GOLD_GIVEN
L0.SuperGoldGiven = L1
ChaosBarrack0 = L0
L0 = {}
L0.IsDestroyed = false
L0.MeleeHPBonus = 0
L0.MeleeDamageBonus = 0
L0.MeleeGoldBonus = 0
L0.MeleeExpBonus = 0
L1 = MELEE_EXP_GIVEN
L0.MeleeExpGiven = L1
L1 = MELEE_GOLD_GIVEN
L0.MeleeGoldGiven = L1
L0.ArcherHPBonus = 0
L0.ArcherDamageBonus = 0
L0.ArcherGoldBonus = 0
L0.ArcherExpBonus = 0
L1 = ARCHER_EXP_GIVEN
L0.ArcherExpGiven = L1
L1 = ARCHER_GOLD_GIVEN
L0.ArcherGoldGiven = L1
L0.CasterHPBonus = 0
L0.CasterDamageBonus = 0
L0.CasterGoldBonus = 0
L0.CasterExpBonus = 0
L1 = CASTER_EXP_GIVEN
L0.CasterExpGiven = L1
L0.SuperHPBonus = 0
L0.SuperDamageBonus = 0
L0.SuperGoldBonus = 0
L0.SuperExpBonus = 0
L1 = SUPER_EXP_GIVEN
L0.SuperExpGiven = L1
L0.NumOfSpawnDisables = 0
L0.WillSpawnSuperMinion = 0
L0.MeleeMinionName = 0
L0.RangedMinionName = 0
L0.CasterMinionName = 0
L1 = CASTER_GOLD_GIVEN
L0.CasterGoldGiven = L1
L0.SuperMinionName = 0
L1 = CASTER_GOLD_GIVEN
L0.SuperGoldGiven = L1
ChaosBarrack1 = L0
L0 = {}
L0.IsDestroyed = false
L0.MeleeHPBonus = 0
L0.MeleeDamageBonus = 0
L0.MeleeGoldBonus = 0
L0.MeleeExpBonus = 0
L1 = MELEE_EXP_GIVEN
L0.MeleeExpGiven = L1
L1 = MELEE_GOLD_GIVEN
L0.MeleeGoldGiven = L1
L0.ArcherHPBonus = 0
L0.ArcherDamageBonus = 0
L0.ArcherGoldBonus = 0
L0.ArcherExpBonus = 0
L1 = ARCHER_EXP_GIVEN
L0.ArcherExpGiven = L1
L1 = ARCHER_GOLD_GIVEN
L0.ArcherGoldGiven = L1
L0.CasterHPBonus = 0
L0.CasterDamageBonus = 0
L0.CasterGoldBonus = 0
L0.CasterExpBonus = 0
L1 = CASTER_EXP_GIVEN
L0.CasterExpGiven = L1
L0.SuperHPBonus = 0
L0.SuperDamageBonus = 0
L0.SuperGoldBonus = 0
L0.SuperExpBonus = 0
L1 = SUPER_EXP_GIVEN
L0.SuperExpGiven = L1
L0.NumOfSpawnDisables = 0
L0.WillSpawnSuperMinion = 0
L0.MeleeMinionName = 0
L0.RangedMinionName = 0
L0.CasterMinionName = 0
L1 = CASTER_GOLD_GIVEN
L0.CasterGoldGiven = L1
L0.SuperMinionName = 0
L1 = CASTER_GOLD_GIVEN
L0.SuperGoldGiven = L1
ChaosBarrack2 = L0
L0 = {}
L0.IsDestroyed = false
L0.MeleeHPBonus = 0
L0.MeleeDamageBonus = 0
L0.MeleeGoldBonus = 0
L0.MeleeExpBonus = 0
L1 = MELEE_EXP_GIVEN
L0.MeleeExpGiven = L1
L1 = MELEE_GOLD_GIVEN
L0.MeleeGoldGiven = L1
L0.ArcherHPBonus = 0
L0.ArcherDamageBonus = 0
L0.ArcherGoldBonus = 0
L0.ArcherExpBonus = 0
L1 = ARCHER_EXP_GIVEN
L0.ArcherExpGiven = L1
L1 = ARCHER_GOLD_GIVEN
L0.ArcherGoldGiven = L1
L0.CasterHPBonus = 0
L0.CasterDamageBonus = 0
L0.CasterGoldBonus = 0
L0.CasterExpBonus = 0
L1 = CASTER_EXP_GIVEN
L0.CasterExpGiven = L1
L0.SuperHPBonus = 0
L0.SuperDamageBonus = 0
L0.SuperGoldBonus = 0
L0.SuperExpBonus = 0
L1 = SUPER_EXP_GIVEN
L0.SuperExpGiven = L1
L0.NumOfSpawnDisables = 0
L0.WillSpawnSuperMinion = 0
L0.MeleeMinionName = 0
L0.RangedMinionName = 0
L0.CasterMinionName = 0
L1 = CASTER_GOLD_GIVEN
L0.CasterGoldGiven = L1
L0.SuperMinionName = 0
L1 = CASTER_GOLD_GIVEN
L0.SuperGoldGiven = L1
OrderBarrack0 = L0
L0 = {}
L0.IsDestroyed = false
L0.MeleeHPBonus = 0
L0.MeleeDamageBonus = 0
L0.MeleeGoldBonus = 0
L0.MeleeExpBonus = 0
L1 = MELEE_EXP_GIVEN
L0.MeleeExpGiven = L1
L1 = MELEE_GOLD_GIVEN
L0.MeleeGoldGiven = L1
L0.ArcherHPBonus = 0
L0.ArcherDamageBonus = 0
L0.ArcherGoldBonus = 0
L0.ArcherExpBonus = 0
L1 = ARCHER_EXP_GIVEN
L0.ArcherExpGiven = L1
L1 = ARCHER_GOLD_GIVEN
L0.ArcherGoldGiven = L1
L0.CasterHPBonus = 0
L0.CasterDamageBonus = 0
L0.CasterGoldBonus = 0
L0.CasterExpBonus = 0
L1 = CASTER_EXP_GIVEN
L0.CasterExpGiven = L1
L0.SuperHPBonus = 0
L0.SuperDamageBonus = 0
L0.SuperGoldBonus = 0
L0.SuperExpBonus = 0
L1 = SUPER_EXP_GIVEN
L0.SuperExpGiven = L1
L0.NumOfSpawnDisables = 0
L0.WillSpawnSuperMinion = 0
L0.MeleeMinionName = 0
L0.RangedMinionName = 0
L0.CasterMinionName = 0
L1 = CASTER_GOLD_GIVEN
L0.CasterGoldGiven = L1
L0.SuperMinionName = 0
L1 = CASTER_GOLD_GIVEN
L0.SuperGoldGiven = L1
OrderBarrack1 = L0
L0 = {}
L0.IsDestroyed = false
L0.MeleeHPBonus = 0
L0.MeleeDamageBonus = 0
L0.MeleeGoldBonus = 0
L0.MeleeExpBonus = 0
L1 = MELEE_EXP_GIVEN
L0.MeleeExpGiven = L1
L1 = MELEE_GOLD_GIVEN
L0.MeleeGoldGiven = L1
L0.ArcherHPBonus = 0
L0.ArcherDamageBonus = 0
L0.ArcherGoldBonus = 0
L0.ArcherExpBonus = 0
L1 = ARCHER_EXP_GIVEN
L0.ArcherExpGiven = L1
L1 = ARCHER_GOLD_GIVEN
L0.ArcherGoldGiven = L1
L0.CasterHPBonus = 0
L0.CasterDamageBonus = 0
L0.CasterGoldBonus = 0
L0.CasterExpBonus = 0
L1 = CASTER_EXP_GIVEN
L0.CasterExpGiven = L1
L0.SuperHPBonus = 0
L0.SuperDamageBonus = 0
L0.SuperGoldBonus = 0
L0.SuperExpBonus = 0
L1 = SUPER_EXP_GIVEN
L0.SuperExpGiven = L1
L0.NumOfSpawnDisables = 0
L0.WillSpawnSuperMinion = 0
L0.MeleeMinionName = 0
L0.RangedMinionName = 0
L0.CasterMinionName = 0
L1 = CASTER_GOLD_GIVEN
L0.CasterGoldGiven = L1
L0.SuperMinionName = 0
L1 = CASTER_GOLD_GIVEN
L0.SuperGoldGiven = L1
OrderBarrack2 = L0
L0 = {}
L1 = ChaosBarrack0
L2 = ChaosBarrack1
L3 = ChaosBarrack2
L0[1] = L1
L0[2] = L2
L0[3] = L3
ChaosBarracksBonuses = L0
L0 = {}
L1 = OrderBarrack0
L2 = OrderBarrack1
L3 = OrderBarrack2
L0[1] = L1
L0[2] = L2
L0[3] = L3
OrderBarracksBonuses = L0
L0 = {}
L0.Turret2 = true
L0.Turret1 = true
L0.Barracks = true
L0.HQTower2 = true
L0.HQTower1 = true
L0.HQ = true
OrderBuildingStatus = L0
L0 = {}
L0.Turret1 = true
L0.Barracks = true
L0.HQTower2 = true
L0.HQTower1 = true
L0.HQ = true
ChaosBuildingStatus = L0
L0 = 0
TotalNumberOfMinions = L0
function L0()
  local L0, L1, L2, L3, L4, L5, L6
  for L3, L4 in L0, L1, L2 do
    L5 = PreloadCharacter
    L6 = L4
    L5(L6)
  end
  for L3, L4 in L0, L1, L2 do
    L5 = PreloadCharacter
    L6 = L4
    L5(L6)
  end
  L0(L1)
  L0(L1)
  L0(L1)
  L0(L1)
  L0(L1)
  L3, L4, L5, L6 = L1()
  L0(L1, L2, L3, L4, L5, L6)
  L0.WaveSpawnRate = 30000
  L0.NumOfMeleeMinionsPerWave = 0
  L0.NumOfArcherMinionsPerWave = 0
  L0.SingleMinionSpawnDelay = 800
  L0.DidPowerGroup = false
  L3 = false
  L0(L1, L2, L3)
end
OnLevelInit = L0
function L0()
  local L0, L1
  L0 = LoadScriptIntoScript
  L1 = "CreateLevelProps.lua"
  L0(L1)
  L0 = CreateLevelProps
  L0()
end
OnPostLevelLoad = L0
function L0(A0)
  local L1
  L1 = TEAM_CHAOS
  if A0 == L1 then
    L1 = TEAM_ORDER
    return L1
  else
    L1 = TEAM_CHAOS
    return L1
  end
end
OppositeTeam = L0
function L0(A0, A1, A2, A3, A4)
  local L5, L6, L7
  L5 = SpawnTable
  TableForBarrack = L5
  L5 = TableForBarrack
  L5 = L5.DidPowerGroup
  if L5 then
    L5 = TableForBarrack
    L6 = TableForBarrack
    L6 = L6.NumOfCasterMinionsPerWave
    L6 = L6 - 1
    L5.NumOfCasterMinionsPerWave = L6
    L5 = TableForBarrack
    L5.DidPowerGroup = false
  end
  L5 = A1 % 4
  if L5 == 0 then
    L5 = TableForBarrack
    L6 = TableForBarrack
    L6 = L6.NumOfCasterMinionsPerWave
    L6 = L6 + 1
    L5.NumOfCasterMinionsPerWave = L6
    L5 = TableForBarrack
    L5.DidPowerGroup = true
  end
  L5 = 0
  L6 = TEAM_ORDER
  if A3 == L6 then
    L6 = OrderBarracksBonuses
    L7 = A0 + 1
    L5 = L6[L7]
  else
    L6 = ChaosBarracksBonuses
    L7 = A0 + 1
    L5 = L6[L7]
  end
  L6 = TableForBarrack
  L7 = EXP_GIVEN_RADIUS
  L6.ExpRadius = L7
  L6 = TableForBarrack
  L6 = L6.NumOfMeleeMinionsPerWave
  lNumOfMeleeMinionsPerWave = L6
  L6 = TableForBarrack
  L6 = L6.NumOfArcherMinionsPerWave
  lNumOfArcherMinionsPerWave = L6
  L6 = TableForBarrack
  L6 = L6.NumOfCasterMinionsPerWave
  lNumOfCasterMinionsPerWave = L6
  L6 = TableForBarrack
  L6 = L6.NumOfSuperMinionsPerWave
  lNumOfSuperMinionsPerWave = L6
  L6 = LAST_WAVE
  if A4 ~= L6 then
    L6 = 6
    BARRACKSCOUNT = L6
    L6 = MAX_MINIONS_EVER
    L7 = GetTotalTeamMinionsSpawned
    L7 = L7()
    L6 = L6 - L7
    totalMinionsRemaining = L6
    L6 = totalMinionsRemaining
    L7 = BARRACKSCOUNT
    L7 = L7 * 7
    if L6 <= L7 then
      L6 = totalMinionsRemaining
      if L6 <= 0 then
        L6 = "None"
        SPECIAL_MINION_MODE = L6
      else
        L6 = totalMinionsRemaining
        L7 = BARRACKSCOUNT
        L7 = L7 * 3
        if L6 >= L7 then
          L6 = "3Archers"
          SPECIAL_MINION_MODE = L6
        else
          L6 = totalMinionsRemaining
          L7 = BARRACKSCOUNT
          if L6 >= L7 then
            L6 = "SpecialPowerMinion"
            SPECIAL_MINION_MODE = L6
          else
            L6 = "None"
            SPECIAL_MINION_MODE = L6
          end
        end
      end
    else
      L6 = ""
      SPECIAL_MINION_MODE = L6
    end
    LAST_WAVE = A4
  end
  L6 = SPECIAL_MINION_MODE
  if L6 == "3Archers" then
    L6 = 0
    lNumOfMeleeMinionsPerWave = L6
    L6 = 3
    lNumOfArcherMinionsPerWave = L6
    L6 = 0
    lNumOfCasterMinionsPerWave = L6
    L6 = 0
    lNumOfSuperMinionsPerWave = L6
  else
    L6 = SPECIAL_MINION_MODE
    if L6 == "SpecialPowerMinion" then
      L6 = 0
      lNumOfMeleeMinionsPerWave = L6
      L6 = 0
      lNumOfArcherMinionsPerWave = L6
      L6 = 0
      lNumOfCasterMinionsPerWave = L6
      L6 = 2
      lNumOfSuperMinionsPerWave = L6
    else
      L6 = SPECIAL_MINION_MODE
      if L6 == "None" then
        L6 = 0
        lNumOfMeleeMinionsPerWave = L6
        L6 = 0
        lNumOfArcherMinionsPerWave = L6
        L6 = 0
        lNumOfCasterMinionsPerWave = L6
        L6 = 0
        lNumOfSuperMinionsPerWave = L6
      end
    end
  end
  L6 = L5.WillSpawnSuperMinion
  if L6 == 1 then
    L6 = 1
    lNumOfSuperMinionsPerWave = L6
    L6 = 0
    lNumOfCasterMinionsPerWave = L6
  end
  L6 = TEAM_ORDER
  if A3 == L6 then
    L6 = OrderNames
    L6 = L6.MeleeMinionName
    L5.MeleeMinionName = L6
    L6 = OrderNames
    L6 = L6.ArcherMinionName
    L5.ArcherMinionName = L6
    L6 = OrderNames
    L6 = L6.CasterMinionName
    L5.CasterMinionName = L6
    L6 = OrderNames
    L6 = L6.SuperMinionName
    L5.SuperMinionName = L6
  else
    L6 = ChaosNames
    L6 = L6.MeleeMinionName
    L5.MeleeMinionName = L6
    L6 = ChaosNames
    L6 = L6.ArcherMinionName
    L5.ArcherMinionName = L6
    L6 = ChaosNames
    L6 = L6.CasterMinionName
    L5.CasterMinionName = L6
    L6 = ChaosNames
    L6 = L6.SuperMinionName
    L5.SuperMinionName = L6
  end
  L6 = {}
  L7 = lNumOfMeleeMinionsPerWave
  L6.NumOfMeleeMinionsPerWave = L7
  L7 = lNumOfArcherMinionsPerWave
  L6.NumOfArcherMinionsPerWave = L7
  L7 = lNumOfCasterMinionsPerWave
  L6.NumOfCasterMinionsPerWave = L7
  L7 = lNumOfSuperMinionsPerWave
  L6.NumOfSuperMinionsPerWave = L7
  L7 = TableForBarrack
  L7 = L7.WaveSpawnRate
  L6.WaveSpawnRate = L7
  L7 = TableForBarrack
  L7 = L7.SingleMinionSpawnDelay
  L6.SingleMinionSpawnDelay = L7
  L7 = L5.MeleeMinionName
  L6.MeleeMinionName = L7
  L7 = L5.ArcherMinionName
  L6.ArcherMinionName = L7
  L7 = L5.CasterMinionName
  L6.CasterMinionName = L7
  L7 = L5.SuperMinionName
  L6.SuperMinionName = L7
  L7 = L5.IsDestroyed
  L6.IsDestroyed = L7
  L7 = L5.MeleeHPBonus
  L6.MeleeHPBonus = L7
  L7 = L5.MeleeDamageBonus
  L6.MeleeDamageBonus = L7
  L7 = L5.MeleeExpGiven
  L6.MeleeExpGiven = L7
  L7 = L5.MeleeGoldGiven
  L6.MeleeGoldGiven = L7
  L7 = L5.ArcherHPBonus
  L6.ArcherHPBonus = L7
  L7 = L5.ArcherDamageBonus
  L6.ArcherDamageBonus = L7
  L7 = L5.ArcherExpGiven
  L6.ArcherExpGiven = L7
  L7 = L5.ArcherGoldGiven
  L6.ArcherGoldGiven = L7
  L7 = L5.CasterHPBonus
  L6.CasterHPBonus = L7
  L7 = L5.CasterDamageBonus
  L6.CasterDamageBonus = L7
  L7 = L5.CasterExpGiven
  L6.CasterExpGiven = L7
  L7 = L5.CasterGoldGiven
  L6.CasterGoldGiven = L7
  L7 = L5.SuperHPBonus
  L6.SuperHPBonus = L7
  L7 = L5.SuperDamageBonus
  L6.SuperDamageBonus = L7
  L7 = L5.SuperExpGiven
  L6.SuperExpGiven = L7
  L7 = L5.SuperGoldGiven
  L6.SuperGoldGiven = L7
  L7 = TableForBarrack
  L7 = L7.ExpRadius
  L6.ExperienceRadius = L7
  ReturnTable = L6
  L6 = ReturnTable
  return L6
end
GetMinionSpawnInfo = L0
function L0(A0, A1)
  local L2, L3, L4
  L3 = TEAM_ORDER
  if A0 == L3 then
    L3 = OrderBarracksBonuses
    L4 = A1 + 1
    L2 = L3[L4]
  else
    L3 = ChaosBarracksBonuses
    L4 = A1 + 1
    L2 = L3[L4]
  end
  return L2
end
GetLuaBarracks = L0
function L0(A0, A1)
  local L2, L3, L4
  L2 = GetLuaBarracks
  L3 = A1
  L4 = A0
  L2 = L2(L3, L4)
  barrack = L2
  L2 = DISABLE_MINION_SPAWN_BASE_TIME
  L3 = DISABLE_MINION_SPAWN_MAG_TIME
  L4 = barrack
  L4 = L4.NumOfSpawnDisables
  L3 = L3 * L4
  L2 = L2 + L3
  return L2
end
GetDisableMinionSpawnTime = L0
function L0(A0, A1)
  local L2, L3, L4
  L2 = GetBarracks
  L3 = A1
  L4 = A0
  L2 = L2(L3, L4)
  cLangBarracks = L2
  L2 = GetLuaBarracks
  L3 = A1
  L4 = A0
  L2 = L2(L3, L4)
  luaBarrack = L2
  L2 = SetDisableMinionSpawn
  L3 = cLangBarracks
  L4 = 500000000
  L2(L3, L4)
  L2 = luaBarrack
  L3 = luaBarrack
  L3 = L3.NumOfSpawnDisables
  L3 = L3 + 1
  L2.NumOfSpawnDisables = L3
end
DisableBarracksSpawn = L0
L0 = 0
BonusesCounter = L0
function L0(A0, A1)
  local L2, L3, L4
  L2 = BonusesCounter
  L2 = L2 + 1
  BonusesCounter = L2
  L2 = OrderBarracksBonuses
  L2 = L2[1]
  L3 = OrderBarracksBonuses
  L3 = L3[1]
  L3 = L3.MeleeHPBonus
  L4 = MELEE_HEALTH_INHIBITOR
  L3 = L3 + L4
  L2.MeleeHPBonus = L3
  L2 = OrderBarracksBonuses
  L2 = L2[1]
  L3 = OrderBarracksBonuses
  L3 = L3[1]
  L3 = L3.MeleeDamageBonus
  L4 = MELEE_DAMAGE_INHIBITOR
  L3 = L3 + L4
  L2.MeleeDamageBonus = L3
  L2 = OrderBarracksBonuses
  L2 = L2[1]
  L3 = OrderBarracksBonuses
  L3 = L3[1]
  L3 = L3.ArcherHPBonus
  L4 = ARCHER_HEALTH_INHIBITOR
  L3 = L3 + L4
  L2.ArcherHPBonus = L3
  L2 = OrderBarracksBonuses
  L2 = L2[1]
  L3 = OrderBarracksBonuses
  L3 = L3[1]
  L3 = L3.ArcherDamageBonus
  L4 = ARCHER_DAMAGE_INHIBITOR
  L3 = L3 + L4
  L2.ArcherDamageBonus = L3
  L2 = OrderBarracksBonuses
  L2 = L2[1]
  L3 = OrderBarracksBonuses
  L3 = L3[1]
  L3 = L3.CasterHPBonus
  L4 = CASTER_HEALTH_INHIBITOR
  L3 = L3 + L4
  L2.CasterHPBonus = L3
  L2 = OrderBarracksBonuses
  L2 = L2[1]
  L3 = OrderBarracksBonuses
  L3 = L3[1]
  L3 = L3.CasterDamageBonus
  L4 = CASTER_DAMAGE_INHIBITOR
  L3 = L3 + L4
  L2.CasterDamageBonus = L3
  L2 = OrderBarracksBonuses
  L2 = L2[1]
  L3 = OrderBarracksBonuses
  L3 = L3[1]
  L3 = L3.SuperHPBonus
  L4 = SUPER_HEALTH_INHIBITOR
  L3 = L3 + L4
  L2.SuperHPBonus = L3
  L2 = OrderBarracksBonuses
  L2 = L2[1]
  L3 = OrderBarracksBonuses
  L3 = L3[1]
  L3 = L3.SuperDamageBonus
  L4 = SUPER_DAMAGE_INHIBITOR
  L3 = L3 + L4
  L2.SuperDamageBonus = L3
  L2 = OrderBarracksBonuses
  L2 = L2[1]
  L3 = OrderBarracksBonuses
  L3 = L3[1]
  L3 = L3.MeleeExpGiven
  L4 = MELEE_EXP_INHIBITOR
  L3 = L3 - L4
  L2.MeleeExpGiven = L3
  L2 = OrderBarracksBonuses
  L2 = L2[1]
  L3 = OrderBarracksBonuses
  L3 = L3[1]
  L3 = L3.MeleeGoldGiven
  L4 = MELEE_GOLD_INHIBITOR
  L3 = L3 - L4
  L2.MeleeGoldGiven = L3
  L2 = OrderBarracksBonuses
  L2 = L2[1]
  L3 = OrderBarracksBonuses
  L3 = L3[1]
  L3 = L3.ArcherExpGiven
  L4 = ARCHER_EXP_INHIBITOR
  L3 = L3 - L4
  L2.ArcherExpGiven = L3
  L2 = OrderBarracksBonuses
  L2 = L2[1]
  L3 = OrderBarracksBonuses
  L3 = L3[1]
  L3 = L3.MeleeGoldGiven
  L4 = ARCHER_GOLD_INHIBITOR
  L3 = L3 - L4
  L2.ArcherGoldGiven = L3
  L2 = OrderBarracksBonuses
  L2 = L2[1]
  L3 = OrderBarracksBonuses
  L3 = L3[1]
  L3 = L3.CasterExpGiven
  L4 = CASTER_EXP_INHIBITOR
  L3 = L3 - L4
  L2.CasterExpGiven = L3
  L2 = OrderBarracksBonuses
  L2 = L2[1]
  L3 = OrderBarracksBonuses
  L3 = L3[1]
  L3 = L3.MeleeGoldGiven
  L4 = CASTER_EXP_INHIBITOR
  L3 = L3 - L4
  L2.CasterGoldGiven = L3
  L2 = OrderBarracksBonuses
  L2 = L2[1]
  L3 = OrderBarracksBonuses
  L3 = L3[1]
  L3 = L3.SuperExpGiven
  L4 = SUPER_EXP_INHIBITOR
  L3 = L3 - L4
  L2.SuperExpGiven = L3
  L2 = OrderBarracksBonuses
  L2 = L2[1]
  L3 = OrderBarracksBonuses
  L3 = L3[1]
  L3 = L3.MeleeGoldGiven
  L4 = SUPER_EXP_INHIBITOR
  L3 = L3 - L4
  L2.SuperGoldGiven = L3
  L2 = OrderBarracksBonuses
  L2 = L2[1]
  L2.WillSpawnSuperMinion = 1
end
ApplyBarracksDestructionBonuses = L0
