function ASCENSIONOnInit()
  PreloadCharacter("Xerath")
  PreloadSpell("AscRandomRespawn")
  PreloadSpell("AscDefenseBuff")
  PreloadSpell("AscOffenseBuff")
  PreloadSpell("AscDebugEvent")
  ApplyPersistentBuffToAllChampions("AscRandomRespawn", false)
  ApplyPersistentBuffToAllChampions("AscDefenseBuff", false)
  ApplyPersistentBuffToAllChampions("AscDebugEvent", false)
end
